In [24]:
import numpy as np

In [336]:
##python driver.py bfs 1,2,5,3,4,0,6,7,8 ## test case

### Class state, starting with BFS

class State():
    
    def __init__(self,board):
        self.board = board_box(board) ### fetch a 3x3 matrix that represents that board
        self.queue = []### que
        self.finished_board = np.array([[0,1,2],
                                       [3,4,5],
                                       [6,7,8]]) ### finished board
        self.visited_states=[] ### store  visited states here
        min_idx = np.where(self.board == np.min(self.board)) ## find the starting indexes on the board
        row_num = min_idx[0][0]
        col_num = min_idx[1][0]
        self.curr_row = row_num
        self.curr_col = col_num
        self.path_taken = []
    def enqueue(self,item):
        self.queue.insert(0,item)
    def dequeue(self):
        move = self.queue.pop() ## get the last item out of the queue
        number_of_move_taken, move_taken = move[0],move[1] ## break into the text and the number
        
        self.path_taken.insert(0,move_taken)
        self.board_swap(move_taken,'actual')
        
        current_pointer = np.where(self.board == number_of_move_taken) ## find the index of where that number is on the board
        row_num = current_pointer[0][0]
        col_num = current_pointer[1][0]
        ### change the current row and col pointers
        self.curr_row = row_num
        self.curr_col = col_num
        
        
        
        
        return move
    def size(self):
        return len(self.queue)
    def move(self): # Move once
        pieces = []
        try:
            up = self.board[self.curr_row-1,self.curr_col] ## Up
            #print(self.board_swap('up','test'),'up test')
            if self.board_swap('up','test') not in self.visited_states: ### do not allow the algo to visit states again
                self.enqueue((up,'up'))
                self.visited_states.append(self.board_swap('up','test').flatten())
            else:
                print('up broke')
        except :
            pass
        try:
            down = self.board[self.curr_row+1,self.curr_col] 
            if self.board_swap('down','test') not in self.visited_states: ### do not allow the algo to visit states again
                self.enqueue((down,'down'))
                self.visited_states.append(self.board_swap('down','test').flatten())
            else:
                print('down broke')
        except:
            pass
        try:
            left = self.board[self.curr_row,self.curr_col-1] 
            #print(self.board_swap('left','test') , 'testing left')
            if self.board_swap('left','test') not in self.visited_states: ### do not allow the algo to visit states again
                self.enqueue((left,'left'))
                self.visited_states.append(self.board_swap('left','test').flatten())
            else:
                print('left broke')
        except:
            pass
        try:
            right = self.board[self.curr_row,self.curr_col+1]
            #print(self.board_swap('right','test') , 'testing right')
            if self.board_swap('right','test') not in self.visited_states: ### do not allow the algo to visit states again
                self.enqueue((right,'right'))
                self.visited_states.append(self.board_swap('right','test').flatten())
            else:
                print('right broke')
        except:
            pass
    def board_swap(self,s_type,test_or_actual):
        self.test_board = self.board.copy()
        if test_or_actual =='actual': ### permantely change the board
            if s_type == 'up':
                self.board[self.curr_row,self.curr_col] ,self.board[self.curr_row-1,self.curr_col] = \
                self.board[self.curr_row-1,self.curr_col], self.board[self.curr_row,self.curr_col]
            elif s_type == 'down':
                self.board[self.curr_row,self.curr_col] ,self.board[self.curr_row+1,self.curr_col]  = \
                self.board[self.curr_row+1,self.curr_col] , self.board[self.curr_row,self.curr_col]
            elif s_type =='left':
                self.board[self.curr_row,self.curr_col] ,self.board[self.curr_row,self.curr_col-1]   = \
                self.board[self.curr_row,self.curr_col-1]  , self.board[self.curr_row,self.curr_col]
            elif s_type =='right':
                self.board[self.curr_row,self.curr_col] ,self.board[self.curr_row,self.curr_col+1]  = \
                self.board[self.curr_row,self.curr_col+1], self.board[self.curr_row,self.curr_col]        
        elif test_or_actual =='test': ## don't change the board
            if s_type == 'up':
                self.test_board[self.curr_row,self.curr_col] ,self.test_board[self.curr_row-1,self.curr_col] = \
                self.test_board[self.curr_row-1,self.curr_col], self.test_board[self.curr_row,self.curr_col]
                return self.test_board
            elif s_type == 'down':
                self.test_board[self.curr_row,self.curr_col] ,self.test_board[self.curr_row+1,self.curr_col]  = \
                self.test_board[self.curr_row+1,self.curr_col] , self.test_board[self.curr_row,self.curr_col]
                return self.test_board
            elif s_type =='left':
                self.test_board[self.curr_row,self.curr_col] ,self.test_board[self.curr_row,self.curr_col-1]   = \
                self.test_board[self.curr_row,self.curr_col-1]  , self.test_board[self.curr_row,self.curr_col]
                return self.test_board
            elif s_type =='right':
                self.test_board[self.curr_row,self.curr_col] ,self.test_board[self.curr_row,self.curr_col+1]  = \
                self.test_board[self.curr_row,self.curr_col+1], self.test_board[self.curr_row,self.curr_col]
                return self.test_board
            
            
    

In [196]:
t = [1,2,5,3,0,4,6,7,8 ]

In [73]:
f = np.zeros((3,3))

def board_box(game_numbers):
    f = np.zeros((3,3))
    row_num = 0
    col_num = 0
    for idx, number in enumerate(game_numbers):
        if col_num ==2:
            f[row_num,col_num]=number
            col_num=0
            row_num+=1
        else:
            f[row_num,col_num]=number
            col_num+=1
    return f


    

In [88]:
np.where(board_box(t) == np.min(board_box(t)))[1][0]

2

In [200]:
r = board_box(t)
r

array([[ 1.,  2.,  5.],
       [ 3.,  0.,  4.],
       [ 6.,  7.,  8.]])

In [198]:
r[1,2] ,r[0,2] =r[0,2],r[1,2]

In [239]:
r

array([[ 1.,  2.,  5.],
       [ 3.,  0.,  4.],
       [ 6.,  7.,  8.]])

In [337]:
s = State(t)

In [338]:
s.board

array([[ 1.,  2.,  5.],
       [ 3.,  0.,  4.],
       [ 6.,  7.,  8.]])

In [339]:
s.move()

/Users/jonathanhilgart/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:56: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
/Users/jonathanhilgart/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:66: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
/Users/jonathanhilgart/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:76: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.


In [340]:
s.queue

[(4.0, 'right'), (3.0, 'left'), (7.0, 'down'), (2.0, 'up')]

In [341]:
s.dequeue()

(2.0, 'up')

In [342]:
s.curr_col

1

In [343]:
s.curr_row

1

In [344]:
s.path_taken

['up']

In [345]:
s.board

array([[ 1.,  0.,  5.],
       [ 3.,  2.,  4.],
       [ 6.,  7.,  8.]])

In [349]:
s.move()

/Users/jonathanhilgart/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:47: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
/Users/jonathanhilgart/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:56: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
/Users/jonathanhilgart/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:66: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
/Users/jonathanhilgart/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:76: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.


In [350]:
s.queue

[(4.0, 'right'),
 (3.0, 'left'),
 (7.0, 'down'),
 (0.0, 'up'),
 (4.0, 'right'),
 (3.0, 'left'),
 (7.0, 'down'),
 (0.0, 'up'),
 (4.0, 'right'),
 (3.0, 'left'),
 (7.0, 'down')]

In [351]:
s.board

array([[ 1.,  0.,  5.],
       [ 3.,  2.,  4.],
       [ 6.,  7.,  8.]])

In [315]:
s.path_taken

['up']

In [317]:
s.dequeue()

(7.0, 'down')